{{- if .Values.signaling.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}-signaling
data:
  server.conf: |
    [server]
    listen = 0.0.0.0:8080

    [appinfo]
    id = spreed

    [mcu]
    type = {{ .Values.signaling.mcu.type }}
    url = {{ .Values.signaling.mcu.url }}

    [turn]
    apikey = {{ .Values.signaling.turn.secret }}
    secret = {{ .Values.signaling.turn.secret }}
    servers = {{ .Values.signaling.turn.server }}
    protocols = {{ .Values.signaling.turn.protocols }}

    [nats]
    url = nats://{{ .Release.Name }}-nats:4222
{{- end -}}