{{- if .Values.signaling.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-signaling
  labels:
    app: {{ .Release.Name }}-signaling
spec:
  replicas: {{ .Values.signaling.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-signaling
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-signaling
    spec:
      containers:
        - name: signaling
          image: "{{ .Values.signaling.image }}"
          imagePullPolicy: {{ .Values.signaling.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /config
          args: ["--config", "/config/server.conf"]
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-signaling
  labels:
    app: {{ .Release.Name }}-signaling
spec:
  type: {{ .Values.signaling.service.type }}
  ports:
    - port: {{ .Values.signaling.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-signaling
{{- end -}}